### ISSUE TITLE
[Bug] The **length** is not updated in `RBTree::clear()`

### ISSUE THREAD

**Issue by lucassong-mh** [tickbh/rbtree-rs#5]
https://github.com/tickbh/rbtree-rs/blob/e786632453eb74ebf76d4720aba939e5dc48a222/src/lib.rs#L1194C1-L1199C6

It seems `self.len` is not reset to zero in `RBTree::clear()`

**Comment by tickbh** [comment]
ok, thank you for remind it, not in 0.2.0 version, I fix it and add doc test

**Comment by lucassong-mh** [comment]
Thanks and appreciate to let me know when 0.2.0 releases.
